git_commit: e84e4a4
batch_size: 8
seed: 1772499093
system:
  flux: 6
  radius: null
  d: 0.1
  nspins:
  - 2
  - 0
  interaction_strength: 1.0
  lz_center: 0.0
  lz_penalty: 0.0
  l2_penalty: 0.0
  interaction_type: coulomb
network:
  type: psiformer
  orbital: full
  psiformer:
    num_heads: 4
    heads_dim: 64
    num_layers: 2
    determinants: 1
mcmc:
  steps: 10
  width: 0.1
  burn_in: 200
  adapt_frequency: 100
optim:
  iterations: 25
  optimizer: adam
  adam:
    lr:
      rate: 0.005
      decay: 1.0
      delay: 2000.0
  kfac:
    lr:
      rate: 0.05
      decay: 1.0
      delay: 2000.0
log:
  save_path: null
  restore_path: null
  save_time_interval: 600
  save_step_interval: 1000
  initial_energy: true
